export const SHOPIFY_WEBHOOKS_OPTIONS = 'SHOPIFY_WEBHOOKS_OPTIONS';
export const SHOPIFY_WEBHOOKs_CONTROLLER_PATH_HACK =
  'SHOPIFY_WEBHOOKs_CONTROLLER_PATH_HACK';

export const SHOPIFY_WEBHOOKS_DEFAULT_PATH = '/shopify/webhooks';
