export const AUTH_MODE_KEY = 'shopify:authMode';

export const SHOPIFY_ACCESS_MODE = 'SHOPIFY_ACCESS_MODE';
export const SHOPIFY_AUTH_OPTIONS = 'SHOPIFY_AUTH_OPTIONS';
export const SHOPIFY_AUTH_CONTROLLER_HACK = 'SHOPIFY_AUTH_CONTROLLER_HACK';
