export const SHOPIFY_API_CONTEXT = 'SHOPIFY_API_CONTEXT';

export const SHOPIFY_API_SESSION_STORAGE = 'SHOPIFY_API_SESSION_STORAGE';

export const SHOPIFY_PRIVATE_APP_SHARED_SECRET = 'SHOPIFY_PRIVATE_APP_SHARED_SECRET';
